name: cuy jobs
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build project
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          ./docker.sh --build-image
      - name: Clean project
        run: |
          ./docker.sh --clean
      - name: Build project
        run: |
          ./docker.sh --build

